services:
  openldap-notifications:
    build:
      context: .docker
      dockerfile: ldap/Dockerfile
    container_name: openldap-notifications
    command: '--loglevel debug'
    init: true
    ports:
      - 389:389
      - 636:636
    environment:
      - 'LDAP_BACKEND=bdb'
      - 'LDAP_ORGANISATION="GIP RECIA"'
      - 'LDAP_DOMAIN=esco-centre.fr'
      - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
      - 'LDAP_ADMIN_PASSWORD=admin'
      - 'LDAP_READONLY_USER:"false"'
    volumes:
      - notifications-ldap-data:/var/lib/ldap
      - notifications-ldap-config:/etc/ldap/slapd.d
volumes:
  notifications-ldap-data: null
  notifications-ldap-config: null
